---
- name: softwares from chocolatey
  hosts: kakish
  become: true


  tasks:

    #Google Chrome
  - name: Install googlechrome
      win_chocolatey:
      name: googlechrome
      version: '111.0.5563.111'
      source: http://internal/odata/repo
      state: present

    #NotePad++
  - name: Install notepadplusplus.install
      win_chocolatey:
      name: notepadplusplus.install
      version: '8.5.1'
      source: http://internal/odata/repo
      state: present
  
    #7Zip
  - name: Install 7zip.install
      win_chocolatey:
      name: 7zip.install
      version: '22.1'
      source: http://internal/odata/repo
      state: present

    #VLC
  - name: Install vlc
      win_chocolatey:
      name: vlc
      version: '3.0.18'
      source: http://internal/odata/repo
      state: present

    #Git
  - name: Install git.install
      win_chocolatey:
      name: git.install
      version: '2.40.0'
      source: http://internal/odata/repo
      state: present
